// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-07-09 18:22:31.679071564 +0800 CST m=+0.022677033

package docs

import (
	"github.com/swaggo/swag"
	"io/ioutil"
)

var doc string

type s struct{}

func init() {
	b, err := ioutil.ReadFile("docs/swagger/swagger.json")
	if err != nil {
		panic("swagger配置文件读取失败: " + err.Error())
	}
	doc = string(b)
}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
